/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CAL_H_RPCGEN
#define _CAL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct variable {
	int x;
	int y;
	int ans;
	int choice;
};
typedef struct variable variable;

#define calc_prg 0x32345676
#define calc_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define calc 1
extern  int * calc_1(variable *, CLIENT *);
extern  int * calc_1_svc(variable *, struct svc_req *);
extern int calc_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calc 1
extern  int * calc_1();
extern  int * calc_1_svc();
extern int calc_prg_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_variable (XDR *, variable*);

#else /* K&R C */
extern bool_t xdr_variable ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CAL_H_RPCGEN */
